name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Make setup script executable
        run: chmod +x setup.sh
          
      - name: Build static files
        run: |
          mkdir -p build
          streamlit run app.py --server.headless true --browser.serverAddress 0.0.0.0 --server.port 8501 &
          sleep 10
          wget -r -k -p -E -nd http://localhost:8501 -P build/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build 